### ISSUE TITLE
analogReference(uint8_t mode) function not implemented

### ISSUE THREAD

**Issue by fgaetani** [arduino/ArduinoCore-nRF528x-mbedos#11]
Unfortunately, I noticed that the analogReference(uint8_t mode) function is not implemented in wiring_analog.cpp. It would be useful to have a function that uses the internal voltage reference at 0.6V and the relative multiplier. I await updates.

**Comment by facchinm** [comment]
Hi @fgaetani ,
thanks for spotting this, I'll be working on a fix soon :wink:

**Comment by fgaetani** [comment]
Hi @facchinm, are there any news regarding this implementation? Thank you!

**Comment by facchinm** [comment]
No news unfortunately, mbed code still configures the channel on init() (https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/analogin_api.c#L96) so overriding it is impossible ATM. 
Anyway it could be a target of https://github.com/arduino/ArduinoCore-nRF528x-mbedos/pull/31 if I find some time to complete it.

**Comment by fgaetani** [comment]
Ok thank you very much, I hope soon!

**Comment by Gerriko** [comment]
Any update on this?

I quite like Adafruit's implementation although no idea how they've done it.

https://learn.adafruit.com/introducing-the-adafruit-nrf52840-feather/nrf52-adc

**Comment by facchinm** [comment]
`analogReference` is now implemented for nRF52 microcontrollers on https://github.com/arduino/ArduinoCore-mbed (beta version, can be tested by downloading Portenta core from Board manager) or [beta branch](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/pull/81).
Testing and reporting results is, as always, appreciated :slightly_smiling_face:
