### ISSUE TITLE
Internal RTC {Enhanced Functionality}

### ISSUE THREAD

**Issue by GuntasSinghProg5** [arduino/ArduinoCore-nRF528x-mbedos#111]
On Pg 82 of the nRF52840's datasheet, it states that there is a 32.768 kHz RC Oscillator. Can an Arduino library be created to use the functionality of this SoC's internal RTC?
Regards
Guntas

**Comment by facchinm** [comment]
Hi @GuntasSinghProg5 ,
right now there's no (official) Arduino library to interact with the RTC, but you can use mbed RTC APIs (https://os.mbed.com/docs/mbed-os/v6.4/apis/time-apis.html)
