### ISSUE TITLE
Compiling Issue for use of Servo.h Library

### ISSUE THREAD

**Issue by andamado997** [arduino/ArduinoCore-nRF528x-mbedos#13]
I was trying to make a test sketch to control a servo using my new Nano 33 Sense BLE board, I then received this error when I tried to compile the program:

 WARNING: library Servo claims to run on (avr, megaavr, sam, samd, nrf52, stm32f4) architecture(s) and may be incompatible with your current board which runs on (mbed) architecture(s).
In file included from C:\Users\DellPC\AppData\Local\Temp\Temp1_Arduino Board Code.zip\ServoBody\ServoBody.ino:1:0:

C:\Users\DellPC\Documents\Arduino\libraries\Servo\src/Servo.h:75:2: error: #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

 #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

  ^~~~~

Multiple libraries were found for "Servo.h"
 Used: C:\Users\DellPC\Documents\Arduino\libraries\Servo
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\libraries\Servo
exit status 1
Error compiling for board Arduino Nano 33 BLE.

Can I expect this issue to resolve this in the very near future? I can understand that its a fairly new piece of hardware but I wasn't aware that there was no current support for the Servo.h Library, which I need to use for an upcoming project. I'd hate to have to return and exchange for another Arduino board since I like the variety of sensors loaded on the Nano 33 Sense.

**Comment by facchinm** [comment]
@andamado997 the porting will be ready very soon, don't worry :wink: I'll keep you posted as soon as there's a pull request ready so you can test it before merge.

**Comment by andamado997** [comment]
Sounds Good! Keep us posted.

**Comment by facchinm** [comment]
Hi @andamado997 ,
I opened the pull request here https://github.com/arduino-libraries/Servo/pull/32
If you could test it and report back ? Thanks!

**Comment by andamado997** [comment]
Just did a test compile on my IDE and it seems like that did it. I'll try a more involved test with the board and a motor later today to make double sure. Thanks again!

**Comment by Netguykb** [comment]
Has there been a resolution to a NEW servo library that will work with Nano 33 BLE??

**Comment by facchinm** [comment]
Hi @Netguykb ,
the code was merged but the lib was not released, my bad. Just did it now, it should be available on library manager in an hour more or less.

**Comment by Netguykb** [comment]
@facchinm Thanks for the update. I assume the library you're referring to is the Arduino Library Manager. If so whats the name I can use to search for this update? Thanks again!

**Comment by facchinm** [comment]
Simply `Servo` :slightly_smiling_face:

**Comment by Netguykb** [comment]
> Simply `Servo` 🙂

Ok, But there 47 of them with the name 'Servo'

The two I have loaded are:
EduIntro by Arduino LLC Version 0.0.12
Servo by Michael Margolis, Arduino Version 1.1.6

Are any of these two yours? Thanks again!

**Comment by per1234** [comment]
>Servo by Michael Margolis, Arduino Version 1.1.6

That's the one.
