### ISSUE TITLE
No low power mode possible

### ISSUE THREAD

**Issue by Knowless** [arduino/ArduinoCore-nRF528x-mbedos#22]
Hello, everybody,
I read that the BLE part of the processor runs on its own. Now I wanted to put the main processor into sleep mode.
Normally the processor should find sleep/deepsleep by itself if there is nothing to do. However, I still measure currents in the examples of about 16mA (Arduino Nano 33 BLE).
So I assume that the sleep-mode is blocked by a function.
Can someone confirm this or give me a clue how to put the controller into sleep mode? I tried the mbed::sleep() command, but without luck too.
It should be possible to send the main core to sleep and maintain the BLE functionality, right?

Greetings,
knowless

**Comment by facchinm** [comment]
No need to call any ::sleep() or similar, mbed already handles it on its own. Please refer to https://github.com/arduino-libraries/ArduinoBLE/issues/37 for a comprehensive answer :wink:
