### ISSUE TITLE
Ports selection disabled

### ISSUE THREAD

**Issue by apas01** [arduino/ArduinoCore-nRF528x-mbedos#25]
Hi,
after succesfully working for some time, the "port" selection is now disabled (grey color).
I'm working on windows 10 (1803 version) and the Arduino IDE is 1.8.10.

The last thing performed was the upload of the attached sketch, that is probably not related.
[codice_gradi.txt](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/files/3747328/codice_gradi.txt)

In the device manager the family "PORT (COM and LPT)" is not present. I could restore legacy hardware but I don't see arduino nano 33 ble drivers in the arduino list.
Any idea?

**Comment by facchinm** [comment]
Hi @apas01 ,
can you try double clicking the reset button? The led will start fading and the board will be in bootloader mode.
If the port appears in this case it means that some code you uploaded crashed it and there is probably some bug in the code

**Comment by apas01** [comment]
You're correct, thank you.
