### ISSUE TITLE
mbedos core - expanded to Nucleo?

### ISSUE THREAD

**Issue by robaol** [arduino/ArduinoCore-nRF528x-mbedos#34]
Hi,
Is there a plan to expand the scope of this core to other mbed os devices, e.g. nucleo boards?

It would make RTOS functionality available to a wide range of boards that are currently supported through stm32duino and maximise the benefit from creating this core, while remaining within the Arduino environment.

BR
Rob

**Comment by facchinm** [comment]
Hi Rob,
there's the plan but it' actually left as an exercise to the user (see https://github.com/arduino/ArduinoCore-nRF528x-mbedos/issues/55) :slightly_smiling_face: 
3rd party cores are encouraged to use this structure and provide support for other boards of course.
