### ISSUE TITLE
Incorrect pin (either diagram or variant.cpp)

### ISSUE THREAD

**Issue by henrygab** [arduino/ArduinoCore-nRF528x-mbedos#46]
The official [**board pinout diagram**](https://content.arduino.cc/assets/Pinout-NANOsense_v1.pdf) says D7 is P0.09, and D8 is P0.10.

However, the BSP v1.1.3 [variant.cpp](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/8b642cc27b7056029357ca1c63d20bd9435ea40c/variants/ARDUINO_NANO33BLE/variant.cpp#L12-L15) says they are 0.23 and P0.21, respectively:

https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/8b642cc27b7056029357ca1c63d20bd9435ea40c/variants/ARDUINO_NANO33BLE/variant.cpp#L12-L15

**_Which of these are correct and should be our source of truth?_**

Can someone validate each of the pin definitions in variant.cpp for correctness?

**Comment by Rocketct** [comment]
Changed and uploaded.

https://store.arduino.cc/usa/nano-33-ble
https://store.arduino.cc/usa/nano-33-ble-sense

i'll close the issue.
