### ISSUE TITLE
pulseIn not implemented

### ISSUE THREAD

**Issue by sandeepmistry** [arduino/ArduinoCore-nRF528x-mbedos#47]
I was using a sketch that depended on `pulseIn`, it seems the core declares it but doesn't contain an implementation, so a linker error happened during the compile:

https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/beac74ca3cd9d07363f66cf9cda6b143e4385cd2/cores/arduino/overloads.h#L29

**Comment by facchinm** [comment]
Fixed by #72
