### ISSUE TITLE
I2C Pullup not yet fixed?

### ISSUE THREAD

**Issue by Talabo** [arduino/ArduinoCore-nRF528x-mbedos#63]
https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/b562318496ca7597174e7041cc05c7cc6c23e0b0/variants/ARDUINO_NANO33BLE/variant.cpp#L77

Does this mean there is a problem with the pull-up resistors for I2C pins? Or it's simply to avoid having it pullup all the time?

**Comment by facchinm** [comment]
There's no problem with I2C and pullups; for maximum power save, the NANO 33 BLE can shutdown all the sensors rails. This is not very well documented and an automatic procedure would probably be better (like moving the initialization to `Wire`) hence the FIXME.
But the functionality is totally ok :slightly_smiling_face:
