### ISSUE TITLE
Add define for SPI_HAS_TRANSACTION

### ISSUE THREAD

**Issue by underseeg** [arduino/ArduinoCore-nRF528x-mbedos#80]
I am new to Arduino development & github but following from a successful fix on https://github.com/nRF24/RF24/issues/537 it seems this core library should have the following define

`#define SPI_HAS_TRANSACTION`

**Comment by facchinm** [comment]
The define is added in ArduinoCore-api which is included in the final core distribution :slightly_smiling_face: Here's the relevant commit https://github.com/arduino/ArduinoCore-nRF528x-mbedos/issues/5#issuecomment-522602664
