### ISSUE TITLE
.C Files not found

### ISSUE THREAD

**Issue by fgaetani** [arduino/ArduinoCore-nRF528x-mbedos#87]
Hi, I am developing a project using Arduino Nano 33 BLE platform. I noticed that all the read and write functions of the digital and analog pins call functions from the gpio_api.h file. It is not clear to me how mbed's HAL abstraction works and how the compiler can compile without c, cpp files.
I tried to search in all folders but found no reference to .c or .cpp files.

I look forward to a response.

Thanks

**Comment by facchinm** [comment]
Hi @fgaetani ,
the whole mbed codebase is being precompiled by `mbed-os-to-arduino` script and archived as a library here https://github.com/arduino/ArduinoCore-nRF528x-mbedos/tree/master/variants/ARDUINO_NANO33BLE/libs -> libmbed.a .
In this way the compilation phase is much faster but all mbed API can still be used
