### ISSUE TITLE
Mbed OS threading primitives not available to Arduino nano 33 IoT

### ISSUE THREAD

**Issue by ScrumFlyer** [arduino/ArduinoCore-nRF528x-mbedos#91]
"rtos" namespace is not available to Arduino nano 33 IoT board.

**Comment by facchinm** [comment]
Hi @ScrumFlyer ,
we use the mbed backend only for Nano33BLE (based on nRF52) and Portenta (STM32H7).
The SAMD21 on Nano33IoT doesn't have enough resources to run the full rtos
